"""Add chave FK produto_id em pedido

Revision ID: 82f9e35f1739
Revises: a2c5582e7771
Create Date: 2023-01-09 13:17:00.338544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f9e35f1739'
down_revision = 'a2c5582e7771'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_produto_pedido', 'produto', ['produto_id'], ['id'])

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint('fk_produto_pedido', type_='foreignkey')

    # ### end Alembic commands ###
