"""Add coluna produto_id em pedido

Revision ID: 9b74325d07b2
Revises: 36c0e66b74c5
Create Date: 2023-01-09 13:12:23.184125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b74325d07b2'
down_revision = '36c0e66b74c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produto_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('produto_id')

    # ### end Alembic commands ###
