"""Add chave estrangeira usuario_id em pedido

Revision ID: a2c5582e7771
Revises: 9b74325d07b2
Create Date: 2023-01-09 13:15:28.827349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2c5582e7771'
down_revision = '9b74325d07b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_usuario_pedido', 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_constraint('fk_usuario_pedido', type_='foreignkey')

    # ### end Alembic commands ###
