"""Criando tabela pedido

Revision ID: afa19c0d9212
Revises: d1585058add3
Create Date: 2023-01-09 13:02:24.489993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa19c0d9212'
down_revision = 'd1585058add3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('entrega', sa.Boolean(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.drop_table('pedido')
    # ### end Alembic commands ###